server:
  port: 8081

spring:
  application:
    name: pass_batch
  datasource:
    url: jdbc:mysql://localhost:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: pass123
    hikari:                         # Spring Boot2부터 default DBCP는 hikariCP입니다.
      maximum-pool-size: 20         # pool에 보관 가능한 최대 connection 수, minimum-idle은 maximum-pool-size를 따라가므로 생략한다.
  batch:
    job:
      enabled: false # 기본값 true는 Spring Boot 실행 시 등록되어 있는 Job들이 실행된다. pass-web프로젝트에서 Job을 API로 실행할 것이기 때문에 false로 설정하였다.
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행합니다. 임베디드인 경우에는 기본적으로 실행하는데, always 설정을 하면 임베디드 타입처럼 항상 활성화시킬 수 있습니다.
      # 초기 수행한 이후에는 꺼두어도 된다.
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
